from __future__ import annotations

VOCABULARY_DATA = [
    {
        "id": "lucid",
        "word": "lucid",
        "pronunciation": "LOO-sid",
        "part_of_speech": "adjective",
        "simple_definition": "clear and easy to understand",
        "advanced_definition": "expressed in a manner that is intellectually clear and free from ambiguity",
        "example_sentence": "Her lucid explanation turned a complex report into actionable insight.",
        "synonyms": ["clear", "coherent", "intelligible"],
        "antonyms": ["confusing", "opaque", "vague"],
        "etymology": "From Latin lucidus, meaning bright or clear.",
        "difficulty": "easy",
        "memory_tip": "Lucid sounds like light, and light helps you see clearly.",
        "confused_with": ["lurid"],
        "category": "communication",
    },
    {
        "id": "pragmatic",
        "word": "pragmatic",
        "pronunciation": "prag-MAT-ik",
        "part_of_speech": "adjective",
        "simple_definition": "focused on practical results",
        "advanced_definition": "dealing with matters in a realistic and results-oriented way rather than idealistic theory",
        "example_sentence": "A pragmatic roadmap helped the team launch despite limited time.",
        "synonyms": ["practical", "realistic", "sensible"],
        "antonyms": ["idealistic", "impractical"],
        "etymology": "From Greek pragma, meaning deed or action.",
        "difficulty": "easy",
        "memory_tip": "Pragmatic people ask: what actually works?",
        "confused_with": ["dogmatic"],
        "category": "professional",
    },
    {
        "id": "ubiquitous",
        "word": "ubiquitous",
        "pronunciation": "yoo-BIK-wi-tus",
        "part_of_speech": "adjective",
        "simple_definition": "found everywhere",
        "advanced_definition": "existing or being present in all places or contexts at once",
        "example_sentence": "Smartphones are ubiquitous in modern urban life.",
        "synonyms": ["everywhere", "pervasive", "universal"],
        "antonyms": ["rare", "scarce"],
        "etymology": "From Latin ubique, meaning everywhere.",
        "difficulty": "medium",
        "memory_tip": "Ubiquitous has ubi like globe coverage everywhere.",
        "confused_with": ["ambiguous"],
        "category": "everyday",
    },
    {
        "id": "cogent",
        "word": "cogent",
        "pronunciation": "KOH-jent",
        "part_of_speech": "adjective",
        "simple_definition": "convincing and logical",
        "advanced_definition": "clear, logical, and persuasive in argument or expression",
        "example_sentence": "She presented a cogent argument for revising the policy.",
        "synonyms": ["compelling", "convincing", "persuasive"],
        "antonyms": ["weak", "unconvincing"],
        "etymology": "From Latin cogere, to drive together.",
        "difficulty": "medium",
        "memory_tip": "Cogent ideas make people go: yes, that makes sense.",
        "confused_with": ["coherent"],
        "category": "academic",
    },
    {
        "id": "ameliorate",
        "word": "ameliorate",
        "pronunciation": "uh-MEEL-yuh-rate",
        "part_of_speech": "verb",
        "simple_definition": "to make something better",
        "advanced_definition": "to improve a condition, especially one that is difficult or undesirable",
        "example_sentence": "The revised workflow will ameliorate onboarding friction.",
        "synonyms": ["improve", "enhance", "alleviate"],
        "antonyms": ["worsen", "aggravate"],
        "etymology": "From Latin melior, meaning better.",
        "difficulty": "hard",
        "memory_tip": "Melior means better: ameliorate means make better.",
        "confused_with": ["immolate"],
        "category": "advanced",
    },
    {
        "id": "ephemeral",
        "word": "ephemeral",
        "pronunciation": "ih-FEM-er-uhl",
        "part_of_speech": "adjective",
        "simple_definition": "lasting for a short time",
        "advanced_definition": "persisting only briefly before disappearing",
        "example_sentence": "Online trends can be intense but ephemeral.",
        "synonyms": ["temporary", "fleeting", "brief"],
        "antonyms": ["enduring", "permanent"],
        "etymology": "From Greek ephemeros, lasting only a day.",
        "difficulty": "medium",
        "memory_tip": "Think of an app story that vanishes in 24 hours.",
        "confused_with": ["eternal"],
        "category": "everyday",
    },
    {
        "id": "meticulous",
        "word": "meticulous",
        "pronunciation": "muh-TIK-yuh-lus",
        "part_of_speech": "adjective",
        "simple_definition": "very careful and precise",
        "advanced_definition": "showing great attention to detail and exactness",
        "example_sentence": "His meticulous notes made revision far easier.",
        "synonyms": ["careful", "thorough", "precise"],
        "antonyms": ["careless", "sloppy"],
        "etymology": "From Latin metus, originally linked to fearfulness in detail.",
        "difficulty": "medium",
        "memory_tip": "Meticulous people catch tiny mistakes.",
        "confused_with": ["methodical"],
        "category": "professional",
    },
    {
        "id": "capricious",
        "word": "capricious",
        "pronunciation": "kuh-PRISH-us",
        "part_of_speech": "adjective",
        "simple_definition": "changing suddenly and unpredictably",
        "advanced_definition": "given to sudden, unaccountable changes of mood or behavior",
        "example_sentence": "Capricious pricing made budgeting nearly impossible.",
        "synonyms": ["erratic", "fickle", "impulsive"],
        "antonyms": ["stable", "consistent"],
        "etymology": "From Italian capriccio, meaning sudden whim.",
        "difficulty": "hard",
        "memory_tip": "Capricious decisions feel random and risky.",
        "confused_with": ["cautious"],
        "category": "test-prep",
    },
    {
        "id": "tenuous",
        "word": "tenuous",
        "pronunciation": "TEN-yoo-us",
        "part_of_speech": "adjective",
        "simple_definition": "weak or not well supported",
        "advanced_definition": "very slight, thin, or lacking solid foundation",
        "example_sentence": "The claim rested on tenuous evidence.",
        "synonyms": ["weak", "fragile", "thin"],
        "antonyms": ["strong", "robust"],
        "etymology": "From Latin tenuis, meaning thin.",
        "difficulty": "hard",
        "memory_tip": "Tenuous sounds like thin and weak.",
        "confused_with": ["tenacious"],
        "category": "academic",
    },
    {
        "id": "laconic",
        "word": "laconic",
        "pronunciation": "luh-KON-ik",
        "part_of_speech": "adjective",
        "simple_definition": "using very few words",
        "advanced_definition": "concise to the point of seeming abrupt",
        "example_sentence": "Her laconic feedback was brief but useful.",
        "synonyms": ["brief", "concise", "succinct"],
        "antonyms": ["verbose", "wordy"],
        "etymology": "From Laconia in ancient Greece, known for terse speech.",
        "difficulty": "hard",
        "memory_tip": "Laconic people speak in short bursts.",
        "confused_with": ["iconic"],
        "category": "advanced",
    },
    {
        "id": "mitigate",
        "word": "mitigate",
        "pronunciation": "MIT-uh-gate",
        "part_of_speech": "verb",
        "simple_definition": "to make less severe",
        "advanced_definition": "to reduce the intensity or seriousness of something harmful",
        "example_sentence": "Backup systems mitigate the risk of data loss.",
        "synonyms": ["reduce", "lessen", "alleviate"],
        "antonyms": ["intensify", "increase"],
        "etymology": "From Latin mitigare, to soften.",
        "difficulty": "medium",
        "memory_tip": "Mitigate means make it milder.",
        "confused_with": ["instigate"],
        "category": "professional",
    },
    {
        "id": "assiduous",
        "word": "assiduous",
        "pronunciation": "uh-SIJ-oo-us",
        "part_of_speech": "adjective",
        "simple_definition": "showing great care and perseverance",
        "advanced_definition": "persistent, diligent, and attentive in sustained effort",
        "example_sentence": "Assiduous practice improved her speaking confidence.",
        "synonyms": ["diligent", "industrious", "dedicated"],
        "antonyms": ["lazy", "negligent"],
        "etymology": "From Latin assiduus, meaning constantly attending.",
        "difficulty": "hard",
        "memory_tip": "Assiduous learners keep showing up daily.",
        "confused_with": ["insidious"],
        "category": "test-prep",
    },
    {
        "id": "nuance",
        "word": "nuance",
        "pronunciation": "NOO-ahns",
        "part_of_speech": "noun",
        "simple_definition": "a subtle difference in meaning",
        "advanced_definition": "a slight distinction in expression, tone, or interpretation",
        "example_sentence": "Great writing often depends on nuance.",
        "synonyms": ["subtlety", "distinction", "shade"],
        "antonyms": ["bluntness", "simplicity"],
        "etymology": "From French nuer, meaning to shade.",
        "difficulty": "medium",
        "memory_tip": "Nuance is the tiny shade between two ideas.",
        "confused_with": ["nuisance"],
        "category": "communication",
    },
    {
        "id": "equivocal",
        "word": "equivocal",
        "pronunciation": "ih-KWIV-uh-kul",
        "part_of_speech": "adjective",
        "simple_definition": "open to more than one interpretation",
        "advanced_definition": "intentionally ambiguous or unclear, often to avoid commitment",
        "example_sentence": "His equivocal answer raised more questions than clarity.",
        "synonyms": ["ambiguous", "uncertain", "vague"],
        "antonyms": ["clear", "definite"],
        "etymology": "From Latin aequus and vocare, equal voice or double meaning.",
        "difficulty": "hard",
        "memory_tip": "Equivocal sounds like equal voices saying different things.",
        "confused_with": ["unequivocal"],
        "category": "academic",
    },
    {
        "id": "resilient",
        "word": "resilient",
        "pronunciation": "ri-ZIL-yunt",
        "part_of_speech": "adjective",
        "simple_definition": "able to recover quickly",
        "advanced_definition": "capable of adapting and bouncing back after stress or adversity",
        "example_sentence": "A resilient learner treats mistakes as feedback.",
        "synonyms": ["tough", "adaptable", "durable"],
        "antonyms": ["fragile", "brittle"],
        "etymology": "From Latin resilire, to spring back.",
        "difficulty": "easy",
        "memory_tip": "Resilient means springing back.",
        "confused_with": ["resistant"],
        "category": "everyday",
    },
    {
        "id": "sagacious",
        "word": "sagacious",
        "pronunciation": "suh-GAY-shus",
        "part_of_speech": "adjective",
        "simple_definition": "wise and insightful",
        "advanced_definition": "having keen mental discernment and sound judgment",
        "example_sentence": "Her sagacious advice prevented a costly mistake.",
        "synonyms": ["wise", "astute", "shrewd"],
        "antonyms": ["foolish", "naive"],
        "etymology": "From Latin sagax, meaning keen or wise.",
        "difficulty": "hard",
        "memory_tip": "A sagacious mentor gives sharp advice.",
        "confused_with": ["salacious"],
        "category": "test-prep",
    },
    {
        "id": "prolific",
        "word": "prolific",
        "pronunciation": "pruh-LIF-ik",
        "part_of_speech": "adjective",
        "simple_definition": "producing a lot",
        "advanced_definition": "highly productive or yielding abundant output",
        "example_sentence": "The prolific author published three books in one year.",
        "synonyms": ["productive", "fruitful", "abundant"],
        "antonyms": ["unproductive", "barren"],
        "etymology": "From Latin proles, meaning offspring.",
        "difficulty": "easy",
        "memory_tip": "Prolific creators make a lot.",
        "confused_with": ["specific"],
        "category": "professional",
    },
    {
        "id": "esoteric",
        "word": "esoteric",
        "pronunciation": "es-uh-TER-ik",
        "part_of_speech": "adjective",
        "simple_definition": "understood by only a few people",
        "advanced_definition": "intended for or likely to be understood by a small, specialized audience",
        "example_sentence": "The paper used esoteric terminology unfamiliar to beginners.",
        "synonyms": ["obscure", "specialized", "arcane"],
        "antonyms": ["common", "mainstream"],
        "etymology": "From Greek esoterikos, belonging to an inner circle.",
        "difficulty": "hard",
        "memory_tip": "Esoteric knowledge belongs to an inner expert circle.",
        "confused_with": ["exoteric"],
        "category": "academic",
    },
    {
        "id": "succinct",
        "word": "succinct",
        "pronunciation": "suk-SINGKT",
        "part_of_speech": "adjective",
        "simple_definition": "brief and clearly expressed",
        "advanced_definition": "concisely and clearly stated without unnecessary detail",
        "example_sentence": "A succinct summary helped everyone align quickly.",
        "synonyms": ["concise", "terse", "brief"],
        "antonyms": ["verbose", "rambling"],
        "etymology": "From Latin succinctus, girded up.",
        "difficulty": "medium",
        "memory_tip": "Succinct writing trims every extra word.",
        "confused_with": ["sequential"],
        "category": "communication",
    },
    {
        "id": "obfuscate",
        "word": "obfuscate",
        "pronunciation": "OB-fuh-skate",
        "part_of_speech": "verb",
        "simple_definition": "to make unclear",
        "advanced_definition": "to deliberately render something difficult to understand",
        "example_sentence": "Buzzwords can obfuscate otherwise simple ideas.",
        "synonyms": ["confuse", "blur", "cloud"],
        "antonyms": ["clarify", "illuminate"],
        "etymology": "From Latin obfuscare, to darken.",
        "difficulty": "hard",
        "memory_tip": "Obfuscate means throw fog over meaning.",
        "confused_with": ["officiate"],
        "category": "advanced",
    },
    {
        "id": "alleviate",
        "word": "alleviate",
        "pronunciation": "uh-LEE-vee-ate",
        "part_of_speech": "verb",
        "simple_definition": "to reduce pain or difficulty",
        "advanced_definition": "to make suffering, deficiency, or burden more bearable",
        "example_sentence": "Practice can alleviate presentation anxiety.",
        "synonyms": ["ease", "relieve", "mitigate"],
        "antonyms": ["worsen", "aggravate"],
        "etymology": "From Latin alleviare, to lighten.",
        "difficulty": "medium",
        "memory_tip": "Alleviate lightens the load.",
        "confused_with": ["elevate"],
        "category": "everyday",
    },
]
